[default]
EXTENSIONS = [
  "crawler_jus.ext.db:init_app",
  "crawler_jus.ext.commands:init_app",
  "crawler_jus.ext.broker:init_app",
  "crawler_jus.api:init_app",
]
MONGO_URI = "mongodb://localhost:27017/crawler"
RABBIT_HOST = "@jinja {{env['RABBIT_HOST']  or 'localhost'}}"

[testing]
EXTENSIONS = [
  "crawler_jus.ext.broker:init_app",
  "crawler_jus.api:init_app",
]
