[default]
EXTENSIONS = [
  "crawler_jus.ext.db:init_app",
  "crawler_jus.ext.commands:init_app",
  "crawler_jus.api:init_app",
]
MONGO_URI = "mongodb://localhost:27017/crawler"

[testing]
EXTENSIONS = [
  "crawler_jus.api:init_app",
]
