[default]
EXTENSIONS = [
  "crawler_jus.ext.commands:init_app",
  "crawler_jus.api:init_app",
]
MONGO_HOST = "@jinja {{env['MONGO_HOST'] or 'localhost'}}"
MONGO_URI = "@jinja mongodb://{{this.MONGO_HOST}}:27017/crawler"

MS_FIRST_INSTANCE = "https://esaj.tjms.jus.br/cpopg5/search.do"
MS_SECOND_INSTANCE = "https://esaj.tjms.jus.br/cposg5/search.do"

AL_FIRST_INSTANCE = "https://www2.tjal.jus.br/cpopg/search.do"
AL_SECOND_INSTANCE = "https://www2.tjal.jus.br/cposg5/search.do"

[testing]
EXTENSIONS = [
  "crawler_jus.api:init_app",
]
